[package]
name = "seclog-sources-cloudtrail"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
seclog-core = { path = "../seclog-core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["clock"] }
