[package]
name = "seclog-formats-parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
parquet = { version = "51.0", features = ["arrow"] }
seclog-core = { path = "../seclog-core" }
serde_json = "1.0"
arrow-array = "51.0"
arrow-schema = "51.0"
